### ISSUE TITLE
Add config file option selector

### ISSUE THREAD

**Issue by geronimo-iia** [flou/brume#1]
Hi,
I thing an optional configuration file selector could be a nice to have.
Something like
```
brume -c brume-other-account-config.xml
```
By this way, we can use same set of troposhere template against several aws account.

If you're agree i can make a pull request :)

See you

**Comment by geronimo-iia** [comment]
To continue, we can with Jinga we can do things like:
```
{% set bucket_name = 'testing-plateform' if (env('SELECTOR') == 'test') else 'other-plateform' %}
```
So, a configuration selector is not so "nice to have". 
May just adding some doc in readme for this use case

**Comment by flou** [comment]
Yes I think the docs should be clearer about the possibilities of the configuration file.

**Comment by geronimo-iia** [comment]
for more complexe usage like call an update on a substack with feed of their dynamic parameter, it's more simple to define another yaml file.
https://github.com/flou/brume/pull/6

With a second pull, I like to add a way to define parameter from outputs of another stack
